export enum NotifierType {
  Success = 'success',
  Warning = 'warning',
  Error = 'error',
  Info = 'info',
}

export enum ErrorPageType {
  NotFound = '404',
  Error = 'error',
}

export enum Teams {
  Dashboard = 'DASHBOARD',
  Alpha = 'ALPHA',
  Dragon = 'DRAGON',
  Ephraim = 'EPHRAIM',
  Epsilon = 'EPSILON',
  Knights = 'KNIGHTS',
  Kronos = 'KRONOS',
  Omega = 'OMEGA',
  Phoenix = 'PHOENIX',
  Sparta = 'SPARTA',
  Viking = 'VIKING',
}

export enum SubTeams {
  Alpha1a = 'Alpha1a',
  Alpha1b = 'Alpha1b',
  Alpha1c = 'Alpha1c',
  Alpha1d = 'Alpha1d',
  Alpha1e = 'Alpha1e',
  Dragon1a = 'Dragon1a',
  Dragon1b = 'Dragon1b',
  Dragon1c = 'Dragon1c',
  Dragon1d = 'Dragon1d',
  Dragon1e = 'Dragon1e',
  Ephraim1a = 'Ephraim1a',
  Ephraim1b = 'Ephraim1b',
  Ephraim1c = 'Ephraim1c',
  Ephraim1d = 'Ephraim1d',
  Ephraim1e = 'Ephraim1e',
  Epsilon1a = 'Epsilon1a',
  Epsilon1b = 'Epsilon1b',
  Epsilon1c = 'Epsilon1c',
  Epsilon1d = 'Epsilon1d',
  Epsilon1e = 'Epsilon1e',
  Knights1a = 'Knights1a',
  Knights1b = 'Knights1b',
  Knights1c = 'Knights1c',
  Knights1d = 'Knights1d',
  Knights1e = 'Knights1e',
  Kronos1a = 'Kronos1a',
  Kronos1b = 'Kronos1b',
  Kronos1c = 'Kronos1c',
  Kronos1d = 'Kronos1d',
  Kronos1e = 'Kronos1e',
  Omega1a = 'Omega1a',
  Omega1b = 'Omega1b',
  Omega1c = 'Omega1c',
  Omega1d = 'Omega1d',
  Omega1e = 'Omega1e',
  Phoenix1a = 'Phoenix1a',
  Phoenix1b = 'Phoenix1b',
  Phoenix1c = 'Phoenix1c',
  Phoenix1d = 'Phoenix1d',
  Phoenix1e = 'Phoenix1e',
  Sparta1a = 'Sparta1a',
  Sparta1b = 'Sparta1b',
  Sparta1c = 'Sparta1c',
  Sparta1d = 'Sparta1d',
  Sparta1e = 'Sparta1e',
  Viking1a = 'Viking1a',
  Viking1b = 'Viking1b',
  Viking1c = 'Viking1c',
  Viking1d = 'Viking1d',
  Viking1e = 'Viking1e',
}
export enum SubReports {
  DueDateSevenPm1a = 'DueDateSevenPm1a',
  DueDateSevenPm1b = 'DueDateSevenPm1b',
  DueDateSevenPm1c = 'DueDateSevenPm1c',
  DueDateSevenPm1d = 'DueDateSevenPm1d',
  DueDateTenAm1a = 'DueDateTenAm1a',
  DueDateTenAm1b = 'DueDateTenAm1b',
  DueDateTenAm1c = 'DueDateTenAm1c',
  DueDateTenAm1d = 'DueDateTenAm1d',
  DueDateOnePm1a = 'DueDateOnePm1a',
  DueDateOnePm1b = 'DueDateOnePm1b',
  DueDateOnePm1c = 'DueDateOnePm1c',
  DueDateOnePm1d = 'DueDateOnePm1d',
  DueDateThreePm1a = 'DueDateThreePm1a',
  DueDateThreePm1b = 'DueDateThreePm1b',
  DueDateThreePm1c = 'DueDateThreePm1c',
  DueDateThreePm1d = 'DueDateThreePm1d',
  DueDateThreePm1e = 'DueDateThreePm1e',
  DueLaterOnedayA = 'DueLaterOnedayA',
  DueLaterOnedayLocationsB = 'DueLaterOnedayLocationsB',
  DueLaterThreedayC = 'DueLaterThreedayC',
  SameDayShippingTwelveAm3a = 'SameDayShippingTwelveAm3a',
  SameDayShippingTwelveAm3b = 'SameDayShippingTwelveAm3b',
  SameDayShippingTwelveAm3c = 'SameDayShippingTwelveAm3c',
  SameDayShippingTwelveAm3d = 'SameDayShippingTwelveAm3d',
  SameDayShippingTwelvePm3a = 'SameDayShippingTwelvePm3a',
  SameDayShippingTwelvePm3b = 'SameDayShippingTwelvePm3b',
  SameDayShippingTwelvePm3c = 'SameDayShippingTwelvePm3c',
  SameDayShippingTwelvePm3d = 'SameDayShippingTwelvePm3d',
  SameDayShippingTwelvePm3e = 'SameDayShippingTwelvePm3e',
  SameDayShippingTwelvePm3f = 'SameDayShippingTwelvePm3f',
  MustGoSevenPm4a1 = 'MustGoSevenPm4a1',
  MustGoSevenPm4a2 = 'MustGoSevenPm4a2',
  MustGoSevenPm4b = 'MustGoSevenPm4b',
  MustGoSevenPm4c = 'MustGoSevenPm4c',
  MustGoSevenPm4d = 'MustGoSevenPm4d',
  MustGoSevenPm4e = 'MustGoSevenPm4e',
  MustGoSevenPm4f = 'MustGoSevenPm4f',
  MustGoSevenPm4g = 'MustGoSevenPm4g',
  MustGoSevenPm4h = 'MustGoSevenPm4h',
  MustGoThreePm4a = 'MustGoThreePm4a',
  MustGoThreePm4b = 'MustGoThreePm4b',
  MustGoThreePm4c = 'MustGoThreePm4c',
  MustGoThreePm4d = 'MustGoThreePm4d',
  MustGoThreePm4e = 'MustGoThreePm4e',
  MustGoThreePm4f = 'MustGoThreePm4f',
  MustGoThreePm4g = 'MustGoThreePm4g',
  MustGoThreePm4h = 'MustGoThreePm4h',
}
export interface Entry {
  tranid: string,
  item: string,
  CustomItemDescription: string,
  CurrentWC: string,
  DueDate: string,
  custbody_wo_current_work_center: string,
  custbody_so_main_duedate: string,
  IdleTime: string,
  shipmethod: string,
  color: string,
}
